### ISSUE TITLE
instructions? 

### ISSUE THREAD

**Issue by ShiroUwUs7** [KorigamiK/kickassanime-downloader#1]
any documentation? i tried using to_update.json to update the anime listed, Im on windows so cant get into the KAA promt.

**Comment by KorigamiK** [comment]
Hey, thanks for trying to use this program. 

I will add the documentation for the installation and usage, I just haven't got the time.

Meanwhile you can try to make it work by yourself. After you install all the requirements from the `requirements.txt` , you need to rename the files in the `Config` folder and remove the `.eg` from the file names and adjust them however you want. 

The `kaa` command is just an alias to the `cli.py` file.

You can use `python cli.py --help` to understand how to use it or just `python cli.py` to get the menu. 

I'll keep this issue open till I add the documentation.

**Comment by KorigamiK** [comment]
I should also mention that, simple menu is not available on Windows at the moment so the menu may not work for you. I'll fix that issue right now.

**Comment by KorigamiK** [comment]
You can check, I have fixed the issue with selectmenu. Don't worry if you are not able to install selectmenu, It should work without it.

**Comment by KorigamiK** [comment]
You can check the wiki for more information. Tell me if you are able to get it working :D

**Comment by ShiroUwUs7** [comment]
Thank you! I will go ahead and look. Sorry if i sounded a bit rude. Im a windows person slowly thinking about transitioning to linux. Just setting up all the things i need on windows before hand and media management is easier on windows for me!

**Comment by ShiroUwUs7** [comment]
![jkStOA9 1](https://user-images.githubusercontent.com/53096166/119273551-aae63900-bbc8-11eb-9a1c-4c2332b3f8e9.png)

No registry that I could find for HKEY_CURRENT_USER\Software\Microsoft\Command Processor

edit: after adding the registry key and string I still get this: and kaa isnt being registered. 

![ObFm9ML 1](https://user-images.githubusercontent.com/53096166/119273724-732bc100-bbc9-11eb-8ca2-c62f6e6a1965.png)

![I5j6iAM 1](https://user-images.githubusercontent.com/53096166/119273850-0d8c0480-bbca-11eb-9111-4072858107a0.png)

**Comment by ShiroUwUs7** [comment]
And this is what cli gives me when opening it directly: 
![sjeqRoW 1](https://user-images.githubusercontent.com/53096166/119273755-95bdda00-bbc9-11eb-9c40-5aa5865d61bb.png)

even after installing the requirements with pip install -r .txt 
![3RojG32 1](https://user-images.githubusercontent.com/53096166/119273804-d9b0df00-bbc9-11eb-8aeb-8eccfda906b4.png)

**Comment by KorigamiK** [comment]
> And this is what cli gives me when opening it directly:

I have updated the code, you should first download the newer version first.
I think after renaming the `config.eg` files you forgot to check the contents of them in the inside.
If you didn't then you must have not used double quotes.
Since, you are on windows you should change the property in `to_update.json` something like
```
{
    ...
    "download_location": "D:\\Videos\\Anime",
    ...
}
```
Make sure that you escape the backslashes. 
If this doesn't work then you should download the file again and then try again.
Also don't worry about installing simplemenu, it should work without it.

Sorry there were some problems with the doskey command. Since I was not on windows I couldn't test the command. I have updated the wiki with the correct command. Here is what you should use:
```
doskey kaa=cd "C:\path\to\kickassanime-downloader\" ^& python cli.py $*
```

Tell me if it works now.

**Comment by KorigamiK** [comment]
I realize that editing the registry was a bad decision. I have updated the wiki with a better method for using the command.
[Please check this out](https://github.com/KorigamiK/kickassanime-downloader/wiki/Command-alias-Windows)

**Comment by ShiroUwUs7** [comment]
Let me check!

**Comment by KorigamiK** [comment]
Good news! I've finally updated the `Readme` for this project. You can find all the sections dedicated to installation and usage there. I'll be closing this thread for now but please feel free to make another issue for any additions that you feel are necessary.
